/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth/index.vue')['default']
    AuthAll: typeof import('./src/components/AuthAll/index.vue')['default']
    BaseEcharts: typeof import('./src/components/BaseEcharts/index.vue')['default']
    HButton: typeof import('./src/layouts/ui-kit/HButton.vue')['default']
    HCheckList: typeof import('./src/layouts/ui-kit/HCheckList.vue')['default']
    HDialog: typeof import('./src/layouts/ui-kit/HDialog.vue')['default']
    HDropdown: typeof import('./src/layouts/ui-kit/HDropdown.vue')['default']
    HDropdownMenu: typeof import('./src/layouts/ui-kit/HDropdownMenu.vue')['default']
    HInput: typeof import('./src/layouts/ui-kit/HInput.vue')['default']
    HKbd: typeof import('./src/layouts/ui-kit/HKbd.vue')['default']
    HSelect: typeof import('./src/layouts/ui-kit/HSelect.vue')['default']
    HSlideover: typeof import('./src/layouts/ui-kit/HSlideover.vue')['default']
    HTabList: typeof import('./src/layouts/ui-kit/HTabList.vue')['default']
    HToggle: typeof import('./src/layouts/ui-kit/HToggle.vue')['default']
    HTooltip: typeof import('./src/layouts/ui-kit/HTooltip.vue')['default']
    NotAllowed: typeof import('./src/components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    PageMain: typeof import('./src/components/PageMain/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./src/components/SystemInfo/index.vue')['default']
    Trend: typeof import('./src/components/Trend/index.vue')['default']
  }
}
