name: Release

on:
  push:
    branches:
      - main-qj

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

        run: echo "Hello" ${{secrets.ACCESS_TOKEN}}
