name: repo-sync

on:
  # 每天 00:05 自动同步
  schedule:
    - cron: '5 0 * * *'
  # 手动触发部署
  workflow_dispatch:

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:wdzyy/basic-admin.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:newbee_qjj/basic-admin.git
